---
version: "2.1"
services:
  playlistSync:
    image: dregsozworld/plex_playlist_sync
    container_name: playlistSync
    volumes:
      - ~/missing_tracks:/data
      - ~/ppsConf:/caches
    environment:
      - PLEX_URL=http://192.99.99.99:32400
      - PLEX_TOKEN=qwertyuiop
      - PLEX_USERNAME=john@example.com
      - PLEX_PASSWORD=Pa$SwoRD
      - WRITE_MISSING_AS_CSV=1 # If you want to write missing
      - APPEND_SERVICE_SUFFIX=1 # If you want to append service name to playlist name (e.g., " - Spotify")
      - ADD_PLAYLIST_POSTER=1 # If you want to add posters for playlists
      - ADD_PLAYLIST_DESCRIPTION=1 # If you want to add descriptions for playlists
      - APPEND_INSTEAD_OF_SYNC=0 # If you want to only append new tracks and not remove
      - SECONDS_TO_WAIT=43200
      - SPOTIFY_CLIENT_ID=qwertyuiop # Option 1
      - SPOTIFY_REDIRECT_URI=http://localhost:8888/callback # DO NOT CHANGE
      - SPOTIFY_CLIENT_SECRET=qwertyuiop # Option 1
      - SPOTIFY_USER_ID=qwertyuiop # Option 1
      - DEEZER_USER_ID=9999999999 # Option 2
      - DEEZER_PLAYLIST_ID=1313621735 1963962142 # Option 3
    restart: unless-stopped
